/* LPN AI-BI - Vente 4-month extraction
   Run each block separately and export the result using the filename in the comment.
   Oracle/Compiere source database. Read-only SELECT statements only.
*/

/* 01_C_ORDER.csv */
SELECT o.*
FROM C_ORDER o
WHERE o.DATEORDERED >= ADD_MONTHS(TRUNC(SYSDATE), -4)
  AND o.ISSOTRX = 'Y'
  AND o.DOCSTATUS IN ('CO', 'CL')
  AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
ORDER BY o.DATEORDERED, o.C_ORDER_ID;

/* 02_C_ORDERLINE.csv */
SELECT ol.*
FROM C_ORDERLINE ol
JOIN C_ORDER o
    ON o.C_ORDER_ID = ol.C_ORDER_ID
WHERE o.DATEORDERED >= ADD_MONTHS(TRUNC(SYSDATE), -4)
  AND o.ISSOTRX = 'Y'
  AND o.DOCSTATUS IN ('CO', 'CL')
  AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
ORDER BY ol.C_ORDER_ID, ol.LINE, ol.C_ORDERLINE_ID;

/* 03_C_INVOICE.csv */
SELECT i.*
FROM C_INVOICE i
WHERE i.DATEINVOICED >= ADD_MONTHS(TRUNC(SYSDATE), -4)
  AND i.ISSOTRX = 'Y'
  AND i.DOCSTATUS = 'CO'
  AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
ORDER BY i.DATEINVOICED, i.C_INVOICE_ID;

/* 04_C_INVOICELINE.csv */
SELECT il.*
FROM C_INVOICELINE il
JOIN C_INVOICE i
    ON i.C_INVOICE_ID = il.C_INVOICE_ID
WHERE i.DATEINVOICED >= ADD_MONTHS(TRUNC(SYSDATE), -4)
  AND i.ISSOTRX = 'Y'
  AND i.DOCSTATUS = 'CO'
  AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
ORDER BY il.C_INVOICE_ID, il.LINE, il.C_INVOICELINE_ID;

/* 05_C_BPARTNER.csv */
SELECT bp.*
FROM C_BPARTNER bp
WHERE bp.C_BPARTNER_ID IN (
    SELECT o.C_BPARTNER_ID
    FROM C_ORDER o
    WHERE o.DATEORDERED >= ADD_MONTHS(TRUNC(SYSDATE), -4)
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)

    UNION

    SELECT i.C_BPARTNER_ID
    FROM C_INVOICE i
    WHERE i.DATEINVOICED >= ADD_MONTHS(TRUNC(SYSDATE), -4)
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
)
ORDER BY bp.C_BPARTNER_ID;

/* 06_M_PRODUCT.csv */
SELECT p.*
FROM M_PRODUCT p
WHERE p.M_PRODUCT_ID IN (
    SELECT ol.M_PRODUCT_ID
    FROM C_ORDERLINE ol
    JOIN C_ORDER o
        ON o.C_ORDER_ID = ol.C_ORDER_ID
    WHERE o.DATEORDERED >= ADD_MONTHS(TRUNC(SYSDATE), -4)
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
      AND ol.M_PRODUCT_ID IS NOT NULL

    UNION

    SELECT il.M_PRODUCT_ID
    FROM C_INVOICELINE il
    JOIN C_INVOICE i
        ON i.C_INVOICE_ID = il.C_INVOICE_ID
    WHERE i.DATEINVOICED >= ADD_MONTHS(TRUNC(SYSDATE), -4)
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
      AND il.M_PRODUCT_ID IS NOT NULL
)
ORDER BY p.M_PRODUCT_ID;

/* 07_C_DOCTYPE.csv */
SELECT dt.*
FROM C_DOCTYPE dt
WHERE dt.C_DOCTYPE_ID IN (
    1000028, 1000034, 1000032, 1000031,
    1000002, 1000003, 1000004
)
ORDER BY dt.C_DOCTYPE_ID;

/* 08_M_PRODUCT_CATEGORY.csv */
SELECT pc.*
FROM M_PRODUCT_CATEGORY pc
WHERE pc.M_PRODUCT_CATEGORY_ID IN (
    SELECT DISTINCT p.M_PRODUCT_CATEGORY_ID
    FROM M_PRODUCT p
    WHERE p.M_PRODUCT_ID IN (
        SELECT ol.M_PRODUCT_ID
        FROM C_ORDERLINE ol
        JOIN C_ORDER o ON o.C_ORDER_ID = ol.C_ORDER_ID
        WHERE o.DATEORDERED >= ADD_MONTHS(TRUNC(SYSDATE), -4)
          AND o.ISSOTRX = 'Y'
          AND o.DOCSTATUS IN ('CO', 'CL')
          AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
          AND ol.M_PRODUCT_ID IS NOT NULL

        UNION

        SELECT il.M_PRODUCT_ID
        FROM C_INVOICELINE il
        JOIN C_INVOICE i ON i.C_INVOICE_ID = il.C_INVOICE_ID
        WHERE i.DATEINVOICED >= ADD_MONTHS(TRUNC(SYSDATE), -4)
          AND i.ISSOTRX = 'Y'
          AND i.DOCSTATUS = 'CO'
          AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
          AND il.M_PRODUCT_ID IS NOT NULL
    )
      AND p.M_PRODUCT_CATEGORY_ID IS NOT NULL
)
ORDER BY pc.M_PRODUCT_CATEGORY_ID;

/* 09_C_TAX.csv */
SELECT tx.*
FROM C_TAX tx
WHERE tx.C_TAX_ID IN (
    SELECT DISTINCT ol.C_TAX_ID
    FROM C_ORDERLINE ol
    JOIN C_ORDER o ON o.C_ORDER_ID = ol.C_ORDER_ID
    WHERE o.DATEORDERED >= ADD_MONTHS(TRUNC(SYSDATE), -4)
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
      AND ol.C_TAX_ID IS NOT NULL

    UNION

    SELECT DISTINCT il.C_TAX_ID
    FROM C_INVOICELINE il
    JOIN C_INVOICE i ON i.C_INVOICE_ID = il.C_INVOICE_ID
    WHERE i.DATEINVOICED >= ADD_MONTHS(TRUNC(SYSDATE), -4)
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
      AND il.C_TAX_ID IS NOT NULL
)
ORDER BY tx.C_TAX_ID;

/* 10_AD_ORG.csv */
SELECT org.*
FROM AD_ORG org
WHERE org.AD_ORG_ID IN (
    SELECT DISTINCT o.AD_ORG_ID
    FROM C_ORDER o
    WHERE o.DATEORDERED >= ADD_MONTHS(TRUNC(SYSDATE), -4)
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)

    UNION

    SELECT DISTINCT i.AD_ORG_ID
    FROM C_INVOICE i
    WHERE i.DATEINVOICED >= ADD_MONTHS(TRUNC(SYSDATE), -4)
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
)
ORDER BY org.AD_ORG_ID;

