/* LPN AI-BI - Vente 2025 + 2026 export
   Oracle/Compiere source database, Oracle 11g compatible.

   Target period:
     from DATE '2025-01-01' inclusive
     to   DATE '2026-07-01' exclusive

   Export each block separately using the filename in the comment.
   For heavy line tables, export as CSV and keep the quarter suffix.

   Performance rules:
   - No function is applied to date columns in WHERE clauses.
   - Heavy line tables are driven by materialized header IDs.
   - Huge line exports avoid ORDER BY to reduce sort cost.
*/

/* 00_CONTROL_COUNTS_BY_QUARTER.csv */
WITH periods AS (
    SELECT '2025_Q1' AS period_name, DATE '2025-01-01' AS date_from, DATE '2025-04-01' AS date_to FROM DUAL UNION ALL
    SELECT '2025_Q2', DATE '2025-04-01', DATE '2025-07-01' FROM DUAL UNION ALL
    SELECT '2025_Q3', DATE '2025-07-01', DATE '2025-10-01' FROM DUAL UNION ALL
    SELECT '2025_Q4', DATE '2025-10-01', DATE '2026-01-01' FROM DUAL UNION ALL
    SELECT '2026_Q1', DATE '2026-01-01', DATE '2026-04-01' FROM DUAL UNION ALL
    SELECT '2026_Q2', DATE '2026-04-01', DATE '2026-07-01' FROM DUAL
),
order_counts AS (
    SELECT p.period_name, COUNT(o.C_ORDER_ID) AS order_count
    FROM periods p
    LEFT JOIN C_ORDER o
        ON o.DATEORDERED >= p.date_from
       AND o.DATEORDERED < p.date_to
       AND o.ISSOTRX = 'Y'
       AND o.DOCSTATUS IN ('CO', 'CL')
       AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
    GROUP BY p.period_name
),
invoice_counts AS (
    SELECT p.period_name, COUNT(i.C_INVOICE_ID) AS invoice_count
    FROM periods p
    LEFT JOIN C_INVOICE i
        ON i.DATEINVOICED >= p.date_from
       AND i.DATEINVOICED < p.date_to
       AND i.ISSOTRX = 'Y'
       AND i.DOCSTATUS = 'CO'
       AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
    GROUP BY p.period_name
),
delivery_counts AS (
    SELECT p.period_name, COUNT(io.M_INOUT_ID) AS delivery_count
    FROM periods p
    LEFT JOIN M_INOUT io
        ON io.MOVEMENTDATE >= p.date_from
       AND io.MOVEMENTDATE < p.date_to
       AND io.ISSOTRX = 'Y'
       AND io.DOCSTATUS IN ('CO', 'CL')
    GROUP BY p.period_name
)
SELECT
    p.period_name,
    p.date_from,
    p.date_to,
    oc.order_count,
    ic.invoice_count,
    dc.delivery_count
FROM periods p
LEFT JOIN order_counts oc ON oc.period_name = p.period_name
LEFT JOIN invoice_counts ic ON ic.period_name = p.period_name
LEFT JOIN delivery_counts dc ON dc.period_name = p.period_name
ORDER BY p.date_from;

/* 01_C_ORDER_2025_2026.csv */
SELECT o.*
FROM C_ORDER o
WHERE o.DATEORDERED >= DATE '2025-01-01'
  AND o.DATEORDERED < DATE '2026-07-01'
  AND o.ISSOTRX = 'Y'
  AND o.DOCSTATUS IN ('CO', 'CL')
  AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
ORDER BY o.DATEORDERED, o.C_ORDER_ID;

/* 02_C_INVOICE_2025_2026.csv */
SELECT i.*
FROM C_INVOICE i
WHERE i.DATEINVOICED >= DATE '2025-01-01'
  AND i.DATEINVOICED < DATE '2026-07-01'
  AND i.ISSOTRX = 'Y'
  AND i.DOCSTATUS = 'CO'
  AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
ORDER BY i.DATEINVOICED, i.C_INVOICE_ID;

/* 03_M_INOUT_2025_2026.csv */
WITH selected_orders AS (
    SELECT /*+ MATERIALIZE */ o.C_ORDER_ID
    FROM C_ORDER o
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
)
SELECT io.*
FROM M_INOUT io
JOIN selected_orders so ON so.C_ORDER_ID = io.C_ORDER_ID
WHERE io.ISSOTRX = 'Y'
  AND io.DOCSTATUS IN ('CO', 'CL')
ORDER BY io.MOVEMENTDATE, io.M_INOUT_ID;

/* 04_C_ORDERLINE_2025_Q1.csv */
WITH selected_orders AS (
    SELECT /*+ MATERIALIZE */ o.C_ORDER_ID
    FROM C_ORDER o
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2025-04-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
)
SELECT /*+ LEADING(so) USE_NL(ol) */ ol.*
FROM selected_orders so
JOIN C_ORDERLINE ol ON ol.C_ORDER_ID = so.C_ORDER_ID;

/* 05_C_ORDERLINE_2025_Q2.csv */
WITH selected_orders AS (
    SELECT /*+ MATERIALIZE */ o.C_ORDER_ID
    FROM C_ORDER o
    WHERE o.DATEORDERED >= DATE '2025-04-01'
      AND o.DATEORDERED < DATE '2025-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
)
SELECT /*+ LEADING(so) USE_NL(ol) */ ol.*
FROM selected_orders so
JOIN C_ORDERLINE ol ON ol.C_ORDER_ID = so.C_ORDER_ID;

/* 06_C_ORDERLINE_2025_Q3.csv */
WITH selected_orders AS (
    SELECT /*+ MATERIALIZE */ o.C_ORDER_ID
    FROM C_ORDER o
    WHERE o.DATEORDERED >= DATE '2025-07-01'
      AND o.DATEORDERED < DATE '2025-10-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
)
SELECT /*+ LEADING(so) USE_NL(ol) */ ol.*
FROM selected_orders so
JOIN C_ORDERLINE ol ON ol.C_ORDER_ID = so.C_ORDER_ID;

/* 07_C_ORDERLINE_2025_Q4.csv */
WITH selected_orders AS (
    SELECT /*+ MATERIALIZE */ o.C_ORDER_ID
    FROM C_ORDER o
    WHERE o.DATEORDERED >= DATE '2025-10-01'
      AND o.DATEORDERED < DATE '2026-01-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
)
SELECT /*+ LEADING(so) USE_NL(ol) */ ol.*
FROM selected_orders so
JOIN C_ORDERLINE ol ON ol.C_ORDER_ID = so.C_ORDER_ID;

/* 08_C_ORDERLINE_2026_Q1.csv */
WITH selected_orders AS (
    SELECT /*+ MATERIALIZE */ o.C_ORDER_ID
    FROM C_ORDER o
    WHERE o.DATEORDERED >= DATE '2026-01-01'
      AND o.DATEORDERED < DATE '2026-04-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
)
SELECT /*+ LEADING(so) USE_NL(ol) */ ol.*
FROM selected_orders so
JOIN C_ORDERLINE ol ON ol.C_ORDER_ID = so.C_ORDER_ID;

/* 09_C_ORDERLINE_2026_Q2.csv */
WITH selected_orders AS (
    SELECT /*+ MATERIALIZE */ o.C_ORDER_ID
    FROM C_ORDER o
    WHERE o.DATEORDERED >= DATE '2026-04-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
)
SELECT /*+ LEADING(so) USE_NL(ol) */ ol.*
FROM selected_orders so
JOIN C_ORDERLINE ol ON ol.C_ORDER_ID = so.C_ORDER_ID;

/* 10_C_INVOICELINE_2025_Q1.csv */
WITH selected_invoices AS (
    SELECT /*+ MATERIALIZE */ i.C_INVOICE_ID
    FROM C_INVOICE i
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2025-04-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
)
SELECT /*+ LEADING(si) USE_NL(il) */ il.*
FROM selected_invoices si
JOIN C_INVOICELINE il ON il.C_INVOICE_ID = si.C_INVOICE_ID;

/* 11_C_INVOICELINE_2025_Q2.csv */
WITH selected_invoices AS (
    SELECT /*+ MATERIALIZE */ i.C_INVOICE_ID
    FROM C_INVOICE i
    WHERE i.DATEINVOICED >= DATE '2025-04-01'
      AND i.DATEINVOICED < DATE '2025-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
)
SELECT /*+ LEADING(si) USE_NL(il) */ il.*
FROM selected_invoices si
JOIN C_INVOICELINE il ON il.C_INVOICE_ID = si.C_INVOICE_ID;

/* 12_C_INVOICELINE_2025_Q3.csv */
WITH selected_invoices AS (
    SELECT /*+ MATERIALIZE */ i.C_INVOICE_ID
    FROM C_INVOICE i
    WHERE i.DATEINVOICED >= DATE '2025-07-01'
      AND i.DATEINVOICED < DATE '2025-10-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
)
SELECT /*+ LEADING(si) USE_NL(il) */ il.*
FROM selected_invoices si
JOIN C_INVOICELINE il ON il.C_INVOICE_ID = si.C_INVOICE_ID;

/* 13_C_INVOICELINE_2025_Q4.csv */
WITH selected_invoices AS (
    SELECT /*+ MATERIALIZE */ i.C_INVOICE_ID
    FROM C_INVOICE i
    WHERE i.DATEINVOICED >= DATE '2025-10-01'
      AND i.DATEINVOICED < DATE '2026-01-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
)
SELECT /*+ LEADING(si) USE_NL(il) */ il.*
FROM selected_invoices si
JOIN C_INVOICELINE il ON il.C_INVOICE_ID = si.C_INVOICE_ID;

/* 14_C_INVOICELINE_2026_Q1.csv */
WITH selected_invoices AS (
    SELECT /*+ MATERIALIZE */ i.C_INVOICE_ID
    FROM C_INVOICE i
    WHERE i.DATEINVOICED >= DATE '2026-01-01'
      AND i.DATEINVOICED < DATE '2026-04-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
)
SELECT /*+ LEADING(si) USE_NL(il) */ il.*
FROM selected_invoices si
JOIN C_INVOICELINE il ON il.C_INVOICE_ID = si.C_INVOICE_ID;

/* 15_C_INVOICELINE_2026_Q2.csv */
WITH selected_invoices AS (
    SELECT /*+ MATERIALIZE */ i.C_INVOICE_ID
    FROM C_INVOICE i
    WHERE i.DATEINVOICED >= DATE '2026-04-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
)
SELECT /*+ LEADING(si) USE_NL(il) */ il.*
FROM selected_invoices si
JOIN C_INVOICELINE il ON il.C_INVOICE_ID = si.C_INVOICE_ID;

/* 16_M_INOUTLINE_2025_Q1.csv */
WITH selected_inouts AS (
    SELECT /*+ MATERIALIZE */ io.M_INOUT_ID
    FROM M_INOUT io
    JOIN C_ORDER o ON o.C_ORDER_ID = io.C_ORDER_ID
    WHERE io.MOVEMENTDATE >= DATE '2025-01-01'
      AND io.MOVEMENTDATE < DATE '2025-04-01'
      AND io.ISSOTRX = 'Y'
      AND io.DOCSTATUS IN ('CO', 'CL')
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
)
SELECT /*+ LEADING(si) USE_NL(iol) */ iol.*
FROM selected_inouts si
JOIN M_INOUTLINE iol ON iol.M_INOUT_ID = si.M_INOUT_ID;

/* 17_M_INOUTLINE_2025_Q2.csv */
WITH selected_inouts AS (
    SELECT /*+ MATERIALIZE */ io.M_INOUT_ID
    FROM M_INOUT io
    JOIN C_ORDER o ON o.C_ORDER_ID = io.C_ORDER_ID
    WHERE io.MOVEMENTDATE >= DATE '2025-04-01'
      AND io.MOVEMENTDATE < DATE '2025-07-01'
      AND io.ISSOTRX = 'Y'
      AND io.DOCSTATUS IN ('CO', 'CL')
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
)
SELECT /*+ LEADING(si) USE_NL(iol) */ iol.*
FROM selected_inouts si
JOIN M_INOUTLINE iol ON iol.M_INOUT_ID = si.M_INOUT_ID;

/* 18_M_INOUTLINE_2025_Q3.csv */
WITH selected_inouts AS (
    SELECT /*+ MATERIALIZE */ io.M_INOUT_ID
    FROM M_INOUT io
    JOIN C_ORDER o ON o.C_ORDER_ID = io.C_ORDER_ID
    WHERE io.MOVEMENTDATE >= DATE '2025-07-01'
      AND io.MOVEMENTDATE < DATE '2025-10-01'
      AND io.ISSOTRX = 'Y'
      AND io.DOCSTATUS IN ('CO', 'CL')
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
)
SELECT /*+ LEADING(si) USE_NL(iol) */ iol.*
FROM selected_inouts si
JOIN M_INOUTLINE iol ON iol.M_INOUT_ID = si.M_INOUT_ID;

/* 19_M_INOUTLINE_2025_Q4.csv */
WITH selected_inouts AS (
    SELECT /*+ MATERIALIZE */ io.M_INOUT_ID
    FROM M_INOUT io
    JOIN C_ORDER o ON o.C_ORDER_ID = io.C_ORDER_ID
    WHERE io.MOVEMENTDATE >= DATE '2025-10-01'
      AND io.MOVEMENTDATE < DATE '2026-01-01'
      AND io.ISSOTRX = 'Y'
      AND io.DOCSTATUS IN ('CO', 'CL')
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
)
SELECT /*+ LEADING(si) USE_NL(iol) */ iol.*
FROM selected_inouts si
JOIN M_INOUTLINE iol ON iol.M_INOUT_ID = si.M_INOUT_ID;

/* 20_M_INOUTLINE_2026_Q1.csv */
WITH selected_inouts AS (
    SELECT /*+ MATERIALIZE */ io.M_INOUT_ID
    FROM M_INOUT io
    JOIN C_ORDER o ON o.C_ORDER_ID = io.C_ORDER_ID
    WHERE io.MOVEMENTDATE >= DATE '2026-01-01'
      AND io.MOVEMENTDATE < DATE '2026-04-01'
      AND io.ISSOTRX = 'Y'
      AND io.DOCSTATUS IN ('CO', 'CL')
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
)
SELECT /*+ LEADING(si) USE_NL(iol) */ iol.*
FROM selected_inouts si
JOIN M_INOUTLINE iol ON iol.M_INOUT_ID = si.M_INOUT_ID;

/* 21_M_INOUTLINE_2026_Q2.csv */
WITH selected_inouts AS (
    SELECT /*+ MATERIALIZE */ io.M_INOUT_ID
    FROM M_INOUT io
    JOIN C_ORDER o ON o.C_ORDER_ID = io.C_ORDER_ID
    WHERE io.MOVEMENTDATE >= DATE '2026-04-01'
      AND io.MOVEMENTDATE < DATE '2026-07-01'
      AND io.ISSOTRX = 'Y'
      AND io.DOCSTATUS IN ('CO', 'CL')
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
)
SELECT /*+ LEADING(si) USE_NL(iol) */ iol.*
FROM selected_inouts si
JOIN M_INOUTLINE iol ON iol.M_INOUT_ID = si.M_INOUT_ID;

/* 22_C_ALLOCATIONLINE_2025_2026.csv */
WITH selected_invoices AS (
    SELECT /*+ MATERIALIZE */ i.C_INVOICE_ID
    FROM C_INVOICE i
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
)
SELECT al.*
FROM C_ALLOCATIONLINE al
JOIN selected_invoices si ON si.C_INVOICE_ID = al.C_INVOICE_ID
ORDER BY al.DATETRX, al.C_ALLOCATIONLINE_ID;

/* 23_C_ALLOCATIONHDR_2025_2026.csv */
WITH selected_invoice_allocations AS (
    SELECT /*+ MATERIALIZE */ DISTINCT al.C_ALLOCATIONHDR_ID
    FROM C_ALLOCATIONLINE al
    JOIN C_INVOICE i ON i.C_INVOICE_ID = al.C_INVOICE_ID
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
      AND al.C_ALLOCATIONHDR_ID IS NOT NULL
)
SELECT ah.*
FROM C_ALLOCATIONHDR ah
JOIN selected_invoice_allocations sia ON sia.C_ALLOCATIONHDR_ID = ah.C_ALLOCATIONHDR_ID
ORDER BY ah.DATETRX, ah.C_ALLOCATIONHDR_ID;

/* 24_C_PAYMENT_2025_2026.csv */
WITH selected_payments AS (
    SELECT /*+ MATERIALIZE */ DISTINCT al.C_PAYMENT_ID
    FROM C_ALLOCATIONLINE al
    JOIN C_INVOICE i ON i.C_INVOICE_ID = al.C_INVOICE_ID
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
      AND al.C_PAYMENT_ID IS NOT NULL
)
SELECT p.*
FROM C_PAYMENT p
JOIN selected_payments sp ON sp.C_PAYMENT_ID = p.C_PAYMENT_ID
ORDER BY p.DATETRX, p.C_PAYMENT_ID;

/* 25_C_BPARTNER_2025_2026.csv */
WITH selected_bpartners AS (
    SELECT /*+ MATERIALIZE */ DISTINCT o.C_BPARTNER_ID
    FROM C_ORDER o
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
    UNION
    SELECT DISTINCT i.C_BPARTNER_ID
    FROM C_INVOICE i
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
    UNION
    SELECT DISTINCT al.C_BPARTNER_ID
    FROM C_ALLOCATIONLINE al
    JOIN C_INVOICE i ON i.C_INVOICE_ID = al.C_INVOICE_ID
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
)
SELECT bp.*
FROM C_BPARTNER bp
JOIN selected_bpartners sbp ON sbp.C_BPARTNER_ID = bp.C_BPARTNER_ID
ORDER BY bp.C_BPARTNER_ID;

/* 26_M_PRODUCT_2025_2026.csv */
WITH selected_products AS (
    SELECT /*+ MATERIALIZE */ DISTINCT ol.M_PRODUCT_ID
    FROM C_ORDERLINE ol
    JOIN C_ORDER o ON o.C_ORDER_ID = ol.C_ORDER_ID
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
      AND ol.M_PRODUCT_ID IS NOT NULL
    UNION
    SELECT DISTINCT il.M_PRODUCT_ID
    FROM C_INVOICELINE il
    JOIN C_INVOICE i ON i.C_INVOICE_ID = il.C_INVOICE_ID
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
      AND il.M_PRODUCT_ID IS NOT NULL
)
SELECT p.*
FROM M_PRODUCT p
JOIN selected_products sp ON sp.M_PRODUCT_ID = p.M_PRODUCT_ID
ORDER BY p.M_PRODUCT_ID;

/* 27_C_DOCTYPE.csv */
SELECT dt.*
FROM C_DOCTYPE dt
WHERE dt.C_DOCTYPE_ID IN (
    1000028, 1000034, 1000032, 1000031,
    1000002, 1000003, 1000004
)
ORDER BY dt.C_DOCTYPE_ID;

/* 28_C_TAX_2025_2026.csv */
WITH selected_tax AS (
    SELECT /*+ MATERIALIZE */ DISTINCT ol.C_TAX_ID
    FROM C_ORDERLINE ol
    JOIN C_ORDER o ON o.C_ORDER_ID = ol.C_ORDER_ID
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
      AND ol.C_TAX_ID IS NOT NULL
    UNION
    SELECT DISTINCT il.C_TAX_ID
    FROM C_INVOICELINE il
    JOIN C_INVOICE i ON i.C_INVOICE_ID = il.C_INVOICE_ID
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
      AND il.C_TAX_ID IS NOT NULL
)
SELECT tx.*
FROM C_TAX tx
JOIN selected_tax st ON st.C_TAX_ID = tx.C_TAX_ID
ORDER BY tx.C_TAX_ID;

/* 29_AD_ORG_2025_2026.csv */
WITH selected_orgs AS (
    SELECT /*+ MATERIALIZE */ DISTINCT o.AD_ORG_ID
    FROM C_ORDER o
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
    UNION
    SELECT DISTINCT i.AD_ORG_ID
    FROM C_INVOICE i
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
)
SELECT org.*
FROM AD_ORG org
JOIN selected_orgs so ON so.AD_ORG_ID = org.AD_ORG_ID
ORDER BY org.AD_ORG_ID;

/* 30_AD_USER_SALESREPS_2025_2026.csv */
WITH selected_users AS (
    SELECT /*+ MATERIALIZE */ DISTINCT o.SALESREP_ID AS AD_USER_ID
    FROM C_ORDER o
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
      AND o.SALESREP_ID IS NOT NULL
    UNION
    SELECT DISTINCT i.SALESREP_ID
    FROM C_INVOICE i
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
      AND i.SALESREP_ID IS NOT NULL
)
SELECT u.*
FROM AD_USER u
JOIN selected_users su ON su.AD_USER_ID = u.AD_USER_ID
ORDER BY u.AD_USER_ID;

/* 31_M_PRODUCT_CATEGORY_2025_2026.csv */
WITH selected_products AS (
    SELECT /*+ MATERIALIZE */ DISTINCT ol.M_PRODUCT_ID
    FROM C_ORDERLINE ol
    JOIN C_ORDER o ON o.C_ORDER_ID = ol.C_ORDER_ID
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
      AND ol.M_PRODUCT_ID IS NOT NULL
    UNION
    SELECT DISTINCT il.M_PRODUCT_ID
    FROM C_INVOICELINE il
    JOIN C_INVOICE i ON i.C_INVOICE_ID = il.C_INVOICE_ID
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
      AND il.M_PRODUCT_ID IS NOT NULL
)
SELECT pc.*
FROM M_PRODUCT_CATEGORY pc
WHERE pc.M_PRODUCT_CATEGORY_ID IN (
    SELECT DISTINCT p.M_PRODUCT_CATEGORY_ID
    FROM M_PRODUCT p
    JOIN selected_products sp ON sp.M_PRODUCT_ID = p.M_PRODUCT_ID
    WHERE p.M_PRODUCT_CATEGORY_ID IS NOT NULL
)
ORDER BY pc.M_PRODUCT_CATEGORY_ID;

/* 32_M_PRODUCT_TYPE_2025_2026.csv */
WITH selected_products AS (
    SELECT /*+ MATERIALIZE */ DISTINCT ol.M_PRODUCT_ID
    FROM C_ORDERLINE ol
    JOIN C_ORDER o ON o.C_ORDER_ID = ol.C_ORDER_ID
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
      AND ol.M_PRODUCT_ID IS NOT NULL
    UNION
    SELECT DISTINCT il.M_PRODUCT_ID
    FROM C_INVOICELINE il
    JOIN C_INVOICE i ON i.C_INVOICE_ID = il.C_INVOICE_ID
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
      AND il.M_PRODUCT_ID IS NOT NULL
)
SELECT pt.*
FROM M_PRODUCT_TYPE pt
WHERE pt.M_PRODUCT_TYPE_ID IN (
    SELECT DISTINCT p.M_PRODUCT_TYPE_ID
    FROM M_PRODUCT p
    JOIN selected_products sp ON sp.M_PRODUCT_ID = p.M_PRODUCT_ID
    WHERE p.M_PRODUCT_TYPE_ID IS NOT NULL
)
ORDER BY pt.M_PRODUCT_TYPE_ID;

/* 33_M_PRODUCT_THEME_2025_2026.csv */
WITH selected_products AS (
    SELECT /*+ MATERIALIZE */ DISTINCT ol.M_PRODUCT_ID
    FROM C_ORDERLINE ol
    JOIN C_ORDER o ON o.C_ORDER_ID = ol.C_ORDER_ID
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
      AND ol.M_PRODUCT_ID IS NOT NULL
    UNION
    SELECT DISTINCT il.M_PRODUCT_ID
    FROM C_INVOICELINE il
    JOIN C_INVOICE i ON i.C_INVOICE_ID = il.C_INVOICE_ID
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
      AND il.M_PRODUCT_ID IS NOT NULL
)
SELECT th.*
FROM M_PRODUCT_THEME th
WHERE th.M_PRODUCT_THEME_ID IN (
    SELECT DISTINCT p.M_PRODUCT_THEME_ID
    FROM M_PRODUCT p
    JOIN selected_products sp ON sp.M_PRODUCT_ID = p.M_PRODUCT_ID
    WHERE p.M_PRODUCT_THEME_ID IS NOT NULL
)
ORDER BY th.M_PRODUCT_THEME_ID;

/* 34_M_PRODUCT_COLLECTION_2025_2026.csv */
WITH selected_products AS (
    SELECT /*+ MATERIALIZE */ DISTINCT ol.M_PRODUCT_ID
    FROM C_ORDERLINE ol
    JOIN C_ORDER o ON o.C_ORDER_ID = ol.C_ORDER_ID
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
      AND ol.M_PRODUCT_ID IS NOT NULL
    UNION
    SELECT DISTINCT il.M_PRODUCT_ID
    FROM C_INVOICELINE il
    JOIN C_INVOICE i ON i.C_INVOICE_ID = il.C_INVOICE_ID
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
      AND il.M_PRODUCT_ID IS NOT NULL
)
SELECT pcoll.*
FROM M_PRODUCT_COLLECTION pcoll
WHERE pcoll.M_PRODUCT_COLLECTION_ID IN (
    SELECT DISTINCT p.M_PRODUCT_COLLECTION_ID
    FROM M_PRODUCT p
    JOIN selected_products sp ON sp.M_PRODUCT_ID = p.M_PRODUCT_ID
    WHERE p.M_PRODUCT_COLLECTION_ID IS NOT NULL
)
ORDER BY pcoll.M_PRODUCT_COLLECTION_ID;

/* 35_M_PRODUCT_PO_2025_2026.csv */
WITH selected_products AS (
    SELECT /*+ MATERIALIZE */ DISTINCT ol.M_PRODUCT_ID
    FROM C_ORDERLINE ol
    JOIN C_ORDER o ON o.C_ORDER_ID = ol.C_ORDER_ID
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
      AND ol.M_PRODUCT_ID IS NOT NULL
    UNION
    SELECT DISTINCT il.M_PRODUCT_ID
    FROM C_INVOICELINE il
    JOIN C_INVOICE i ON i.C_INVOICE_ID = il.C_INVOICE_ID
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
      AND il.M_PRODUCT_ID IS NOT NULL
)
SELECT po.*
FROM M_PRODUCT_PO po
JOIN selected_products sp ON sp.M_PRODUCT_ID = po.M_PRODUCT_ID
ORDER BY po.M_PRODUCT_ID, po.C_BPARTNER_ID;

/* 36_C_BPARTNER_VENDOR.csv */
SELECT bp.*
FROM C_BPARTNER bp
WHERE bp.ISVENDOR = 'Y'
ORDER BY bp.C_BPARTNER_ID;

/* 37_M_WAREHOUSE_2025_2026.csv */
WITH selected_warehouses AS (
    SELECT /*+ MATERIALIZE */ DISTINCT o.M_WAREHOUSE_ID
    FROM C_ORDER o
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
      AND o.M_WAREHOUSE_ID IS NOT NULL
    UNION
    SELECT DISTINCT io.M_WAREHOUSE_ID
    FROM M_INOUT io
    WHERE io.MOVEMENTDATE >= DATE '2025-01-01'
      AND io.MOVEMENTDATE < DATE '2026-07-01'
      AND io.ISSOTRX = 'Y'
      AND io.DOCSTATUS IN ('CO', 'CL')
      AND io.M_WAREHOUSE_ID IS NOT NULL
)
SELECT wh.*
FROM M_WAREHOUSE wh
JOIN selected_warehouses sw ON sw.M_WAREHOUSE_ID = wh.M_WAREHOUSE_ID
ORDER BY wh.M_WAREHOUSE_ID;

/* 38_M_LOCATOR_2025_2026.csv */
WITH selected_locators AS (
    SELECT /*+ MATERIALIZE */ DISTINCT iol.M_LOCATOR_ID
    FROM M_INOUTLINE iol
    JOIN M_INOUT io ON io.M_INOUT_ID = iol.M_INOUT_ID
    WHERE io.MOVEMENTDATE >= DATE '2025-01-01'
      AND io.MOVEMENTDATE < DATE '2026-07-01'
      AND io.ISSOTRX = 'Y'
      AND io.DOCSTATUS IN ('CO', 'CL')
      AND iol.M_LOCATOR_ID IS NOT NULL
)
SELECT loc.*
FROM M_LOCATOR loc
JOIN selected_locators sl ON sl.M_LOCATOR_ID = loc.M_LOCATOR_ID
ORDER BY loc.M_LOCATOR_ID;

/* 39_RV_STORAGE_CURRENT_FOR_SOLD_PRODUCTS.csv */
WITH selected_products AS (
    SELECT /*+ MATERIALIZE */ DISTINCT ol.M_PRODUCT_ID
    FROM C_ORDERLINE ol
    JOIN C_ORDER o ON o.C_ORDER_ID = ol.C_ORDER_ID
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
      AND ol.M_PRODUCT_ID IS NOT NULL
    UNION
    SELECT DISTINCT il.M_PRODUCT_ID
    FROM C_INVOICELINE il
    JOIN C_INVOICE i ON i.C_INVOICE_ID = il.C_INVOICE_ID
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
      AND il.M_PRODUCT_ID IS NOT NULL
)
SELECT st.*
FROM RV_STORAGE st
JOIN selected_products sp ON sp.M_PRODUCT_ID = st.M_PRODUCT_ID
ORDER BY st.M_PRODUCT_ID, st.M_WAREHOUSE_ID, st.M_LOCATOR_ID;

/* 40_C_BPARTNER_LOCATION_2025_2026.csv */
WITH selected_bpartners AS (
    SELECT /*+ MATERIALIZE */ DISTINCT o.C_BPARTNER_ID
    FROM C_ORDER o
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
    UNION
    SELECT DISTINCT i.C_BPARTNER_ID
    FROM C_INVOICE i
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
)
SELECT bpl.*
FROM C_BPARTNER_LOCATION bpl
JOIN selected_bpartners sbp ON sbp.C_BPARTNER_ID = bpl.C_BPARTNER_ID
ORDER BY bpl.C_BPARTNER_ID, bpl.C_BPARTNER_LOCATION_ID;

/* 41_C_LOCATION_2025_2026.csv */
WITH selected_locations AS (
    SELECT /*+ MATERIALIZE */ DISTINCT bpl.C_LOCATION_ID
    FROM C_BPARTNER_LOCATION bpl
    JOIN (
        SELECT DISTINCT o.C_BPARTNER_ID
        FROM C_ORDER o
        WHERE o.DATEORDERED >= DATE '2025-01-01'
          AND o.DATEORDERED < DATE '2026-07-01'
          AND o.ISSOTRX = 'Y'
          AND o.DOCSTATUS IN ('CO', 'CL')
          AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
        UNION
        SELECT DISTINCT i.C_BPARTNER_ID
        FROM C_INVOICE i
        WHERE i.DATEINVOICED >= DATE '2025-01-01'
          AND i.DATEINVOICED < DATE '2026-07-01'
          AND i.ISSOTRX = 'Y'
          AND i.DOCSTATUS = 'CO'
          AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
    ) sbp ON sbp.C_BPARTNER_ID = bpl.C_BPARTNER_ID
    WHERE bpl.C_LOCATION_ID IS NOT NULL
)
SELECT loc.*
FROM C_LOCATION loc
JOIN selected_locations sl ON sl.C_LOCATION_ID = loc.C_LOCATION_ID
ORDER BY loc.C_LOCATION_ID;

/* 42_CORRECTED_CUSTOMER_PORTFOLIO_2025_2026.csv
   This replaces the unreliable 57_COMMERCIAL_CUSTOMER_PORTFOLIO_24M CA logic.
   Orders and invoices are aggregated separately, then joined to customers.
*/
WITH order_agg AS (
    SELECT
        o.C_BPARTNER_ID,
        COUNT(*) AS ORDER_COUNT,
        MIN(o.DATEORDERED) AS FIRST_ORDER_DATE,
        MAX(o.DATEORDERED) AS LAST_ORDER_DATE,
        SUM(o.GRANDTOTAL) AS ORDERED_CA_TTC
    FROM C_ORDER o
    WHERE o.DATEORDERED >= DATE '2025-01-01'
      AND o.DATEORDERED < DATE '2026-07-01'
      AND o.ISSOTRX = 'Y'
      AND o.DOCSTATUS IN ('CO', 'CL')
      AND o.C_DOCTYPETARGET_ID IN (1000028, 1000034, 1000032, 1000031)
    GROUP BY o.C_BPARTNER_ID
),
invoice_agg AS (
    SELECT
        i.C_BPARTNER_ID,
        COUNT(*) AS INVOICE_COUNT,
        MIN(i.DATEINVOICED) AS FIRST_INVOICE_DATE,
        MAX(i.DATEINVOICED) AS LAST_INVOICE_DATE,
        SUM(i.GRANDTOTAL) AS INVOICED_CA_TTC,
        SUM(CASE WHEN i.ISPAID = 'Y' THEN i.GRANDTOTAL ELSE 0 END) AS PAID_CA_TTC,
        SUM(CASE WHEN NVL(i.ISPAID, 'N') <> 'Y' THEN i.GRANDTOTAL ELSE 0 END) AS UNPAID_CA_TTC
    FROM C_INVOICE i
    WHERE i.DATEINVOICED >= DATE '2025-01-01'
      AND i.DATEINVOICED < DATE '2026-07-01'
      AND i.ISSOTRX = 'Y'
      AND i.DOCSTATUS = 'CO'
      AND i.C_DOCTYPE_ID IN (1000002, 1000003, 1000004)
    GROUP BY i.C_BPARTNER_ID
),
selected_customers AS (
    SELECT C_BPARTNER_ID FROM order_agg
    UNION
    SELECT C_BPARTNER_ID FROM invoice_agg
)
SELECT
    bp.C_BPARTNER_ID,
    bp.VALUE AS CUSTOMER_CODE,
    bp.NAME AS CUSTOMER_NAME,
    bp.NAME2 AS CUSTOMER_NAME2,
    bp.ISCUSTOMER,
    bp.ISVENDOR,
    bp.C_BP_GROUP_ID,
    bg.NAME AS BP_GROUP_NAME,
    bp.SALESREP_ID,
    au.NAME AS SALESREP_NAME,
    bp.C_PAYMENTTERM_ID,
    pt.NAME AS PAYMENTTERM_NAME,
    bp.M_PRICELIST_ID,
    pl.NAME AS PRICELIST_NAME,
    bp.SO_CREDITLIMIT,
    bp.SO_CREDITUSED,
    bp.TOTALOPENBALANCE,
    oa.ORDER_COUNT,
    oa.FIRST_ORDER_DATE,
    oa.LAST_ORDER_DATE,
    oa.ORDERED_CA_TTC,
    ia.INVOICE_COUNT,
    ia.FIRST_INVOICE_DATE,
    ia.LAST_INVOICE_DATE,
    ia.INVOICED_CA_TTC,
    ia.PAID_CA_TTC,
    ia.UNPAID_CA_TTC
FROM selected_customers sc
JOIN C_BPARTNER bp ON bp.C_BPARTNER_ID = sc.C_BPARTNER_ID
LEFT JOIN order_agg oa ON oa.C_BPARTNER_ID = bp.C_BPARTNER_ID
LEFT JOIN invoice_agg ia ON ia.C_BPARTNER_ID = bp.C_BPARTNER_ID
LEFT JOIN C_BP_GROUP bg ON bg.C_BP_GROUP_ID = bp.C_BP_GROUP_ID
LEFT JOIN AD_USER au ON au.AD_USER_ID = bp.SALESREP_ID
LEFT JOIN C_PAYMENTTERM pt ON pt.C_PAYMENTTERM_ID = bp.C_PAYMENTTERM_ID
LEFT JOIN M_PRICELIST pl ON pl.M_PRICELIST_ID = bp.M_PRICELIST_ID
ORDER BY NVL(ia.INVOICED_CA_TTC, 0) DESC, NVL(oa.ORDERED_CA_TTC, 0) DESC, bp.C_BPARTNER_ID;
