from __future__ import annotations

import argparse
import csv
import json
import re
import shutil
import zipfile
from collections.abc import Iterable
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_STAGING_DIR = REPO_ROOT / "Youssef_Extractions" / "vente_clean_import"
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "local-snapshots" / "vente-4months-20260514"
DEFAULT_SNAPSHOT_ID = "lpn-vente-4months-20260514-v1"

INTEGER_NAME_PATTERNS = (
    re.compile(r"(^|_)ID$"),
    re.compile(r"(^|_)ID_\d+$"),
    re.compile(r"(^|_)CREATEDBY$"),
    re.compile(r"(^|_)UPDATEDBY$"),
    re.compile(r"(^|_)LINE$"),
    re.compile(r"(^|_)PRIORITYNO$"),
    re.compile(r"(^|_)DOCUMENTCOPIES$"),
    re.compile(r"(^|_)CREDITCARDEXPMM$"),
    re.compile(r"(^|_)CREDITCARDEXPYY$"),
    re.compile(r"(^|_)GUARANTEEDAYS(MIN)?$"),
    re.compile(r"(^|_)SHELFLIFEDAYS$"),
    re.compile(r"(^|_)GOODFORDAYS$"),
)

NUMERIC_TOKENS = (
    "AMT",
    "AMOUNT",
    "TOTAL",
    "PRICE",
    "QTY",
    "QUANTITY",
    "RATE",
    "VOLUME",
    "WEIGHT",
    "MARGIN",
    "PERCENT",
    "PCT",
    "LIMIT",
    "TAX",
)

TEXT_FORCE_TOKENS = (
    "DOCUMENTNO",
    "VALUE",
    "NAME",
    "DESCRIPTION",
    "HELP",
    "NOTE",
    "STATUS",
    "ACTION",
    "TYPE",
    "RULE",
    "CODE",
    "NO",
    "NUMBER",
    "EMAIL",
    "PHONE",
    "URL",
    "UPC",
    "SKU",
    "TAXID",
    "SERNO",
    "LOT",
    "X",
    "Y",
    "Z",
)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build an importable PostgreSQL zip bundle from vente_clean_import CSVs."
    )
    parser.add_argument("--staging-dir", type=Path, default=DEFAULT_STAGING_DIR)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--sample-rows", type=int, default=2000)
    parser.add_argument(
        "--snapshot-id",
        default=None,
        help="Override the manifest snapshot_id. Defaults to the staging manifest snapshot_id.",
    )
    args = parser.parse_args()

    staging_dir = args.staging_dir.resolve()
    output_root = args.output_root.resolve()
    _validate_paths(staging_dir, output_root)

    bundle_dir = output_root / "bundle"
    csv_dir = bundle_dir / "csv"
    if output_root.exists():
        shutil.rmtree(output_root)
    csv_dir.mkdir(parents=True, exist_ok=True)

    manifest = json.loads((staging_dir / "manifest.json").read_text(encoding="utf-8"))
    snapshot_id = args.snapshot_id or manifest.get("snapshot_id") or DEFAULT_SNAPSHOT_ID
    manifest["snapshot_id"] = snapshot_id
    manifest["exported_at"] = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    manifest["notes"] = (
        f"{manifest.get('notes', '').strip()} Importable PostgreSQL bundle generated by "
        "scripts/build-vente-postgres-bundle.py with inferred PostgreSQL schema."
    ).strip()

    schema_tables: list[str] = []
    inference_report: list[dict[str, Any]] = []
    for table in manifest["tables"]:
        source_csv = staging_dir / table["csv_file"]
        target_csv = bundle_dir / table["csv_file"]
        target_csv.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_csv, target_csv)

        headers, samples = _read_csv_sample(source_csv, args.sample_rows)
        expected_headers = table["exported_columns"]
        if headers != expected_headers:
            raise SystemExit(
                f"Header mismatch for {table['name']}: staging CSV headers differ from manifest"
            )

        columns = [_infer_column(header, [row[index] for row in samples]) for index, header in enumerate(headers)]
        schema_tables.append(_create_table_sql(table["name"], columns))
        inference_report.append(
            {
                "table": table["name"],
                "csv_file": table["csv_file"],
                "sampled_rows": len(samples),
                "columns": columns,
            }
        )

    schema_sql = "\n\n".join(
        [
            "-- Generated by scripts/build-vente-postgres-bundle.py",
            "-- Source: Youssef_Extractions/vente_clean_import",
            *schema_tables,
        ]
    )
    (bundle_dir / "schema.sql").write_text(schema_sql + "\n", encoding="utf-8")
    (bundle_dir / "manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    (output_root / "schema_inference_report.json").write_text(
        json.dumps(inference_report, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    zip_path = output_root / f"{snapshot_id}.zip"
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
        for path in sorted(bundle_dir.rglob("*")):
            if path.is_file():
                archive.write(path, path.relative_to(bundle_dir))

    print(f"Built PostgreSQL import bundle: {zip_path}")
    print(f"Bundle directory: {bundle_dir}")
    print(f"Tables: {len(manifest['tables'])}")
    print(f"Rows: {sum(table['row_count'] for table in manifest['tables'])}")


def _validate_paths(staging_dir: Path, output_root: Path) -> None:
    if not staging_dir.exists():
        raise SystemExit(f"Staging directory does not exist: {staging_dir}")
    if not (staging_dir / "manifest.json").exists():
        raise SystemExit(f"manifest.json is missing from staging directory: {staging_dir}")
    if not (staging_dir / "csv").is_dir():
        raise SystemExit(f"csv directory is missing from staging directory: {staging_dir}")

    expected_parent = (REPO_ROOT / "local-snapshots").resolve()
    try:
        output_root.relative_to(expected_parent)
    except ValueError as exc:
        raise SystemExit(
            "Refusing to write outside local-snapshots. "
            f"Output root was: {output_root}"
        ) from exc


def _read_csv_sample(path: Path, sample_rows: int) -> tuple[list[str], list[list[str]]]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.reader(handle)
        try:
            headers = next(reader)
        except StopIteration as exc:
            raise SystemExit(f"CSV is empty: {path}") from exc
        samples = []
        for row in reader:
            samples.append(row + [""] * (len(headers) - len(row)))
            if len(samples) >= sample_rows:
                break
    return headers, samples


def _infer_column(header: str, values: Iterable[str]) -> dict[str, str]:
    normalized = header.upper()
    non_empty = [value.strip() for value in values if value is not None and value.strip() != ""]

    if _is_timestamp_column(normalized):
        return {"name": header.lower(), "type": "timestamp"}

    if _is_integer_column(normalized) and _all_integer(non_empty):
        return {"name": header.lower(), "type": "bigint"}

    if _is_numeric_column(normalized) and _all_decimal(non_empty):
        return {"name": header.lower(), "type": "numeric"}

    if _is_forced_text_column(normalized):
        return {"name": header.lower(), "type": "text"}

    return {"name": header.lower(), "type": "text"}


def _is_timestamp_column(header: str) -> bool:
    return (
        header in {"CREATED", "UPDATED", "DATETRX", "DATEACCT", "DATEORDERED", "DATEINVOICED"}
        or header.startswith("DATE")
        or header.endswith("DATE")
        or header.endswith("DATETIME")
    )


def _is_forced_text_column(header: str) -> bool:
    if header.startswith("IS") and len(header) > 2:
        return True
    return any(token in header for token in TEXT_FORCE_TOKENS)


def _is_integer_column(header: str) -> bool:
    return any(pattern.search(header) for pattern in INTEGER_NAME_PATTERNS)


def _is_numeric_column(header: str) -> bool:
    return any(token in header for token in NUMERIC_TOKENS)


def _all_integer(values: list[str]) -> bool:
    if not values:
        return True
    for value in values:
        try:
            decimal = Decimal(value)
        except InvalidOperation:
            return False
        if decimal != decimal.to_integral_value():
            return False
    return True


def _all_decimal(values: list[str]) -> bool:
    if not values:
        return True
    for value in values:
        try:
            Decimal(value)
        except InvalidOperation:
            return False
    return True


def _create_table_sql(table_name: str, columns: list[dict[str, str]]) -> str:
    column_lines = [
        f"    {_quote_identifier(column['name'])} {column['type']}" for column in columns
    ]
    return (
        f"CREATE TABLE business.{_quote_identifier(table_name.lower())} (\n"
        + ",\n".join(column_lines)
        + "\n);"
    )


def _quote_identifier(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


if __name__ == "__main__":
    main()
